import type { Candle } from '../../src/types.js';
import type { TradeSignal } from '../signal/signalEngine.js';

export type PaperPositionStatus = 'OPEN' | 'CLOSED';
export type PaperCloseReason = 'TP1' | 'TP2' | 'TP3' | 'STOP' | 'INVALIDATION' | 'MANUAL' | 'TIMEOUT';

export interface PaperAccount { initialCapital:number; equity:number; realizedPnl:number; unrealizedPnl:number; feesPaid:number; slippagePaid:number; peakEquity:number; maxDrawdownPercent:number; halted:boolean; lastMarkPrice:number|null; }
export interface PaperPosition { id:string; symbol:string; direction:'LONG'|'SHORT'; status:PaperPositionStatus; openedAt:number; closedAt:number|null; entryPrice:number; quantity:number; notional:number; stopLoss:number; initialStopLoss:number; takeProfits:{tp1:number;tp2:number;tp3:number}; remainingQuantity:number; realizedPnl:number; unrealizedPnl:number; feesPaid:number; slippagePaid:number; closeReason:PaperCloseReason|null; tp1Hit:boolean; tp2Hit:boolean; breakevenActivated:boolean; lastMarkPrice:number|null; }
export interface PaperTradingConfig { initialCapital?:number; feeBpsPerSide?:number; slippageBpsPerSide?:number; maxRiskPercent?:number; maxOpenPositions?:number; maxDrawdownPercent?:number; partialTpPercent?:number; }
export interface PaperTradingStats { totalTrades:number; winningTrades:number; losingTrades:number; breakevenTrades:number; winRatePercent:number; profitFactor:number; netPnl:number; netPnlPercent:number; averageTradePnl:number; averageR:number; bestTradePnl:number; worstTradePnl:number; tp1HitRatePercent:number; tp2HitRatePercent:number; halted:boolean; }
export interface PaperTradingState { account:PaperAccount; positions:PaperPosition[]; history:PaperPosition[]; stats:PaperTradingStats; }
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
const positive=(v:number)=>Number.isFinite(v)&&v>0;
const round=(v:number,d=8)=>Math.round(v*10**d)/10**d;
export class PaperTradingEngine {
 private readonly config:Required<PaperTradingConfig>; private state:PaperTradingState;
 constructor(config:PaperTradingConfig={}){this.config={initialCapital:positive(config.initialCapital??10000)?config.initialCapital??10000:10000,feeBpsPerSide:clamp(config.feeBpsPerSide??5,0,100),slippageBpsPerSide:clamp(config.slippageBpsPerSide??2,0,100),maxRiskPercent:clamp(config.maxRiskPercent??1,.1,2),maxOpenPositions:Math.max(1,Math.floor(config.maxOpenPositions??1)),maxDrawdownPercent:clamp(config.maxDrawdownPercent??10,1,100),partialTpPercent:clamp(config.partialTpPercent??33.333333,10,90)};this.state=this.emptyState();}
 private emptyStats():PaperTradingStats{return{totalTrades:0,winningTrades:0,losingTrades:0,breakevenTrades:0,winRatePercent:0,profitFactor:0,netPnl:0,netPnlPercent:0,averageTradePnl:0,averageR:0,bestTradePnl:0,worstTradePnl:0,tp1HitRatePercent:0,tp2HitRatePercent:0,halted:false};}
 private emptyState():PaperTradingState{const capital=this.config.initialCapital;return{account:{initialCapital:capital,equity:capital,realizedPnl:0,unrealizedPnl:0,feesPaid:0,slippagePaid:0,peakEquity:capital,maxDrawdownPercent:0,halted:false,lastMarkPrice:null},positions:[],history:[],stats:this.emptyStats()};}
 getState(){return structuredClone(this.state);}
 reset(){this.state=this.emptyState();return this.getState();}
 openFromSignal(signal:TradeSignal,timestamp=Date.now()){if(signal.direction==='NO TRADE'||!signal.entryZone||!signal.stopLoss||!signal.takeProfits||this.state.account.halted||this.state.positions.length>=this.config.maxOpenPositions)return null;const riskPct=Math.min(signal.riskPercent,this.config.maxRiskPercent),riskCash=this.state.account.equity*riskPct/100,entry=signal.entryZone.reference,distance=Math.abs(entry-signal.stopLoss);if(!positive(entry)||!positive(distance)||riskCash<=0)return null;const quantity=riskCash/distance,notional=quantity*entry,entrySlip=entry*this.config.slippageBpsPerSide/10000,executedEntry=signal.direction==='LONG'?entry+entrySlip:entry-entrySlip,fee=notional*this.config.feeBpsPerSide/10000,slippageCost=quantity*Math.abs(executedEntry-entry);const p:PaperPosition={id:`paper-${signal.symbol.replace('/','-')}-${timestamp}-${Math.random().toString(36).slice(2,8)}`,symbol:signal.symbol,direction:signal.direction,status:'OPEN',openedAt:timestamp,closedAt:null,entryPrice:round(executedEntry),quantity:round(quantity),notional:round(notional,4),stopLoss:signal.stopLoss,initialStopLoss:signal.stopLoss,takeProfits:signal.takeProfits,remainingQuantity:round(quantity),realizedPnl:round(-fee-slippageCost),unrealizedPnl:0,feesPaid:round(fee),slippagePaid:round(slippageCost),closeReason:null,tp1Hit:false,tp2Hit:false,breakevenActivated:false,lastMarkPrice:round(executedEntry)};this.state.positions.push(p);this.state.account.realizedPnl-=fee+slippageCost;this.state.account.feesPaid+=fee;this.state.account.slippagePaid+=slippageCost;this.markToMarket(executedEntry);return structuredClone(p);}
 processCandle(candle:Candle,timestamp=candle.timestamp){for(const p of [...this.state.positions]){const hit=this.firstHit(p,candle);if(!hit){if(timestamp-p.openedAt>=32*15*60_000)this.executeClose(p,candle.close,'TIMEOUT',timestamp);continue;}if(hit.reason==='STOP')this.executeClose(p,hit.price,'STOP',timestamp);else if(hit.reason==='TP1'&&!p.tp1Hit){this.executePartialClose(p,hit.price,'TP1',timestamp);p.tp1Hit=true;p.breakevenActivated=true;p.stopLoss=p.entryPrice;}else if(hit.reason==='TP2'&&p.tp1Hit&&!p.tp2Hit){this.executePartialClose(p,hit.price,'TP2',timestamp);p.tp2Hit=true;p.stopLoss=p.entryPrice;}else if(hit.reason==='TP3'&&p.tp2Hit)this.executeClose(p,hit.price,'TP3',timestamp);}this.markToMarket(candle.close,timestamp);}
 markToMarket(price:number,_timestamp=Date.now()){if(!positive(price))return;let unrealized=0;for(const p of this.state.positions){p.lastMarkPrice=round(price);p.unrealizedPnl=round(p.direction==='LONG'?(price-p.entryPrice)*p.remainingQuantity:(p.entryPrice-price)*p.remainingQuantity);unrealized+=p.unrealizedPnl;}this.state.account.unrealizedPnl=round(unrealized);this.state.account.equity=round(this.state.account.initialCapital+this.state.account.realizedPnl+unrealized,4);this.state.account.lastMarkPrice=round(price);this.state.account.peakEquity=Math.max(this.state.account.peakEquity,this.state.account.equity);const dd=this.state.account.peakEquity>0?(this.state.account.peakEquity-this.state.account.equity)/this.state.account.peakEquity*100:0;this.state.account.maxDrawdownPercent=Math.max(this.state.account.maxDrawdownPercent,dd);if(this.state.account.maxDrawdownPercent>=this.config.maxDrawdownPercent)this.state.account.halted=true;this.recalculateStats();}
 close(positionId:string,price:number,reason:PaperCloseReason='MANUAL',timestamp=Date.now()){const p=this.state.positions.find(x=>x.id===positionId);if(!p||!positive(price))return null;this.executeClose(p,price,reason,timestamp);this.markToMarket(price,timestamp);return structuredClone(p);}
 private firstHit(p:PaperPosition,c:Candle){if(p.direction==='LONG'){if(c.low<=p.stopLoss)return{price:p.stopLoss,reason:'STOP' as PaperCloseReason};if(!p.tp1Hit&&c.high>=p.takeProfits.tp1)return{price:p.takeProfits.tp1,reason:'TP1' as PaperCloseReason};if(p.tp1Hit&&!p.tp2Hit&&c.high>=p.takeProfits.tp2)return{price:p.takeProfits.tp2,reason:'TP2' as PaperCloseReason};if(p.tp2Hit&&c.high>=p.takeProfits.tp3)return{price:p.takeProfits.tp3,reason:'TP3' as PaperCloseReason};}else{if(c.high>=p.stopLoss)return{price:p.stopLoss,reason:'STOP' as PaperCloseReason};if(!p.tp1Hit&&c.low<=p.takeProfits.tp1)return{price:p.takeProfits.tp1,reason:'TP1' as PaperCloseReason};if(p.tp1Hit&&!p.tp2Hit&&c.low<=p.takeProfits.tp2)return{price:p.takeProfits.tp2,reason:'TP2' as PaperCloseReason};if(p.tp2Hit&&c.low<=p.takeProfits.tp3)return{price:p.takeProfits.tp3,reason:'TP3' as PaperCloseReason};}return null;}
 private executePartialClose(p:PaperPosition,price:number,_reason:PaperCloseReason,_timestamp:number){if(p.status==='CLOSED')return;const quantity=Math.min(p.remainingQuantity,p.quantity*this.config.partialTpPercent/100);this.executeQuantityClose(p,quantity,price);}
 private executeQuantityClose(p:PaperPosition,quantity:number,price:number){if(p.status==='CLOSED'||quantity<=0)return;const slip=price*this.config.slippageBpsPerSide/10000,executed=p.direction==='LONG'?price-slip:price+slip,gross=p.direction==='LONG'?(executed-p.entryPrice)*quantity:(p.entryPrice-executed)*quantity,fee=Math.abs(executed*quantity)*this.config.feeBpsPerSide/10000,slippageCost=quantity*Math.abs(executed-price),net=gross-fee-slippageCost;p.realizedPnl=round(p.realizedPnl+net);p.feesPaid=round(p.feesPaid+fee);p.slippagePaid=round(p.slippagePaid+slippageCost);p.remainingQuantity=round(Math.max(0,p.remainingQuantity-quantity));p.unrealizedPnl=0;this.state.account.realizedPnl+=net;this.state.account.feesPaid+=fee;this.state.account.slippagePaid+=slippageCost;}
 private executeClose(p:PaperPosition,price:number,reason:PaperCloseReason,timestamp:number){if(p.status==='CLOSED')return;if(p.remainingQuantity>0)this.executeQuantityClose(p,p.remainingQuantity,price);p.remainingQuantity=0;p.unrealizedPnl=0;p.status='CLOSED';p.closedAt=timestamp;p.closeReason=reason;this.state.positions=this.state.positions.filter(x=>x.id!==p.id);this.state.history.push(structuredClone(p));this.recalculateStats();}
 private recalculateStats(){const h=this.state.history,total=h.length,w=h.filter(p=>p.realizedPnl>0).length,l=h.filter(p=>p.realizedPnl<0).length,be=total-w-l,gp=h.reduce((s,p)=>s+Math.max(0,p.realizedPnl),0),gl=Math.abs(h.reduce((s,p)=>s+Math.min(0,p.realizedPnl),0)),net=this.state.account.realizedPnl;const avgR=total?h.reduce((s,p)=>{const risk=Math.abs(p.entryPrice-p.initialStopLoss)*p.quantity;return s+(risk>0?p.realizedPnl/risk:0)},0)/total:0;this.state.stats={totalTrades:total,winningTrades:w,losingTrades:l,breakevenTrades:be,winRatePercent:total?w/total*100:0,profitFactor:gl>0?gp/gl:gp>0?Infinity:0,netPnl:round(net,4),netPnlPercent:this.state.account.initialCapital>0?round(net/this.state.account.initialCapital*100,4):0,averageTradePnl:total?round(net/total,4):0,averageR:round(avgR,4),bestTradePnl:total?round(Math.max(...h.map(p=>p.realizedPnl)),4):0,worstTradePnl:total?round(Math.min(...h.map(p=>p.realizedPnl)),4):0,tp1HitRatePercent:total?h.filter(p=>p.tp1Hit).length/total*100:0,tp2HitRatePercent:total?h.filter(p=>p.tp2Hit).length/total*100:0,halted:this.state.account.halted};}
}
export const createPaperTradingEngine=(config:PaperTradingConfig={})=>new PaperTradingEngine(config);
