import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';
import { createServer as createViteServer } from 'vite';
import { GoogleGenAI } from '@google/genai';
import dotenv from 'dotenv';
import { TradeSignal, SystemNotification } from './src/types.js';
import { fetchTop100Cryptos, syncRealTimePrices, getBrasiliaTimeStr } from './server/realMarketData.js';
import { getMarketSnapshot } from './server/market/marketSnapshotService.js';
import { analyzeMarket } from './server/confluence/marketAnalysisService.js';
import { fetchHistoricalBinanceCandles } from './server/backtest/historicalDataService.js';
import { fetchHistoricalBinanceFunding } from './server/derivatives/historicalFundingService.js';
import { runHistoricalBacktest } from './server/backtest/historicalBacktest.js';
import { generateTradeSignal } from './server/signal/signalEngine.js';
import { fetchRealCandles } from './server/market/candleService.js';
import { buildQuantAnalystPrompt, parseQuantAnalystResponse } from './server/ai/quantAnalyst.js';
import { paperTradingLoop } from './server/paper/paperTradingLoop.js';
import { buildQuantitativeLab } from './server/quant/quantitativeLab.js';
import { validateSelectedParameters } from './server/quant/parameterValidation.js';

dotenv.config();
const __filename = fileURLToPath(import.meta.url); const __dirname = path.dirname(__filename); const app = express(); const PORT = 3000; app.use(express.json());
let genAI: GoogleGenAI | null = null;
if (process.env.GEMINI_API_KEY) { try { genAI = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY, httpOptions: { headers: { 'User-Agent': 'aistudio-build' } } }); } catch (err) { console.error('Error initializing GoogleGenAI:', err); } }
let cachedSignals: TradeSignal[] = []; let cachedNotifications: SystemNotification[] = []; let isRefreshing = false; let lastRefreshTime = 0; let lastSourceInfo = 'Iniciando varredura das 100 maiores criptos por Market Cap...';
async function refreshMarketData(): Promise<void> { if (isRefreshing) return; isRefreshing = true; try { const signals = await fetchTop100Cryptos(); if (signals?.length) { cachedSignals = signals; lastRefreshTime = Date.now(); lastSourceInfo = 'Top 100 Criptomoedas por Market Cap (Tempo Real • CoinGecko + Binance)'; } const validSignals = cachedSignals.filter(s => s.passedFilter); validSignals.forEach(signal => { if (!cachedNotifications.some(n => n.symbol === signal.symbol && Date.now() - n.timestamp < 900000)) { const timeBrasilia = getBrasiliaTimeStr(Date.now(), true); cachedNotifications.unshift({ id: `notif-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`, timestamp: Date.now(), timeStr: timeBrasilia, type: 'CRITICAL_SIGNAL', severity: 'high', symbol: signal.symbol, title: `Setup Quantitativo Confirmado: ${signal.symbol} (#${signal.marketCapRank || 0})`, message: `Confluência institucional atingiu ${signal.confidence}%. Entrada em $${signal.entryPrice} e SL dinâmico em $${signal.stopLoss} (R/R 1:${signal.riskReward}) • ${timeBrasilia} (Horário de Brasília).`, read: false, actionable: true }); } }); cachedSignals.forEach(signal => { if (Math.abs(signal.change24h) >= 7 && !cachedNotifications.some(n => n.symbol === signal.symbol && n.type === 'FUNDING_ALERT' && Date.now() - n.timestamp < 1200000)) { const timeBrasilia = getBrasiliaTimeStr(Date.now(), true); cachedNotifications.unshift({ id: `notif-vol-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`, timestamp: Date.now(), timeStr: timeBrasilia, type: 'FUNDING_ALERT', severity: 'medium', symbol: signal.symbol, title: `Alerta de Volatilidade: ${signal.symbol} (#${signal.marketCapRank || 0})`, message: `Variação de 24h atingiu ${signal.change24h > 0 ? '+' : ''}${signal.change24h}% no ativo #${signal.marketCapRank || 0} • ${timeBrasilia} (Brasília).`, read: false }); } }); if (cachedNotifications.length > 50) cachedNotifications = cachedNotifications.slice(0, 50); } catch (err: any) { console.error('Failed to refresh real-time market data:', err.message); } finally { isRefreshing = false; } }
refreshMarketData(); setInterval(refreshMarketData, 35000); setInterval(async () => { if (cachedSignals.length > 0) { await syncRealTimePrices(); lastRefreshTime = Date.now(); } }, 6000);

app.get('/api/market/candles/:symbol', async (req, res) => { try { const symbol = decodeURIComponent(req.params.symbol).toUpperCase(); if (!/^[A-Z0-9]+\/[A-Z0-9]+$/.test(symbol)) return res.status(400).json({ error: 'Símbolo inválido. Use o formato BTC/USDT.' }); const snapshot = await getMarketSnapshot(symbol, { forceRefresh: req.query.refresh === 'true' }); return res.json({ success: true, source: 'Binance/OKX real OHLCV', snapshot }); } catch (error: any) { console.error('Real market snapshot error:', error); return res.status(502).json({ success: false, error: error?.message || 'Falha ao carregar dados reais de mercado.' }); } });
app.get('/api/market/analysis/:symbol', async (req, res) => { try { const symbol = decodeURIComponent(req.params.symbol).toUpperCase(); if (!/^[A-Z0-9]+\/[A-Z0-9]+$/.test(symbol)) return res.status(400).json({ error: 'Símbolo inválido. Use o formato BTC/USDT.' }); const analysis = await analyzeMarket(symbol, req.query.refresh === 'true'); return res.json({ success: true, source: 'Binance/OKX real OHLCV + indicadores + estrutura + SMC + divergências + Gann + Wyckoff', analysis }); } catch (error: any) { console.error('Quantitative market analysis error:', error); return res.status(502).json({ success: false, error: error?.message || 'Falha ao executar análise quantitativa.' }); } });
app.get('/api/signal/:symbol', async (req, res) => { try { const symbol = decodeURIComponent(req.params.symbol || 'BTC/USDT').toUpperCase().replace('-', '/'); if (!/^[A-Z0-9]+\/[A-Z0-9]+$/.test(symbol)) return res.status(400).json({ success: false, error: 'Símbolo inválido. Use BTC/USDT.' }); const riskPercent = Number(req.query.riskPercent ?? 1); const analysis = await analyzeMarket(symbol, req.query.refresh === 'true'); const series = await fetchRealCandles(symbol, '15m', 500); const signal = generateTradeSignal(analysis, series.candles, Number.isFinite(riskPercent) ? riskPercent : 1); return res.json({ success: true, source: 'Binance/OKX real OHLCV + quantitative signal engine', signal, generatedAt: Date.now() }); } catch (error: any) { console.error('Signal engine error:', error); return res.status(502).json({ success: false, error: error?.message || 'Falha ao gerar sinal.' }); } });
app.get('/api/paper/status', (_req, res) => res.json({ success: true, ...paperTradingLoop.getStatus(), state: paperTradingLoop.getEngine().getState() })); app.post('/api/paper/start', (_req, res) => { paperTradingLoop.start(); res.json({ success: true, ...paperTradingLoop.getStatus() }); }); app.post('/api/paper/stop', (_req, res) => { paperTradingLoop.stop(); res.json({ success: true, ...paperTradingLoop.getStatus() }); }); app.post('/api/paper/tick', async (_req, res) => { await paperTradingLoop.tick(); const status = paperTradingLoop.getStatus(); const success = status.lastError === null; return res.status(success ? 200 : 502).json({ success, ...status, state: paperTradingLoop.getEngine().getState() }); }); app.post('/api/paper/reset', (_req, res) => { paperTradingLoop.stop(); const state = paperTradingLoop.getEngine().reset(); return res.json({ success: true, ...paperTradingLoop.getStatus(), state }); }); app.post('/api/paper/close/:positionId', (req, res) => { const price = Number(req.body?.price); const closed = paperTradingLoop.getEngine().close(req.params.positionId, price, 'MANUAL'); if (!closed) return res.status(404).json({ success: false, error: 'Posição não encontrada ou preço inválido.' }); return res.json({ success: true, position: closed, state: paperTradingLoop.getEngine().getState() }); });
app.get('/api/market/signals', async (_req, res) => { if (!cachedSignals.length) await refreshMarketData(); res.json({ timestamp: lastRefreshTime || Date.now(), version: 'The God Protocol v2026 (v4.0)', dataSource: lastSourceInfo, isRealTime: true, signals: cachedSignals, activeCount: cachedSignals.filter(s => s.passedFilter).length, monitoredCount: cachedSignals.length }); }); app.post('/api/market/refresh-prices', async (_req, res) => { const updatedSignals = await syncRealTimePrices(); lastRefreshTime = Date.now(); res.json({ success: true, timestamp: lastRefreshTime, signals: updatedSignals, activeCount: updatedSignals.filter(s => s.passedFilter).length }); }); app.post('/api/market/scan', async (_req, res) => { await refreshMarketData(); res.json({ success: true, message: 'Varredura quantitativa em tempo real via Binance.US + OKX concluída com sucesso.', dataSource: lastSourceInfo, signals: cachedSignals }); });
app.post('/api/ai-analysis', async (req, res) => { try { const requestedSymbol = typeof req.body?.symbol === 'string' ? req.body.symbol.toUpperCase().replace('-', '/') : 'BTC/USDT'; if (!/^[A-Z0-9]+\/[A-Z0-9]+$/.test(requestedSymbol)) return res.status(400).json({ error: 'Símbolo inválido. Use BTC/USDT.' }); const riskPercent = Number(req.body?.riskPercent ?? 1); const analysis = await analyzeMarket(requestedSymbol, true); const series = await fetchRealCandles(requestedSymbol, '15m', 500); const signal = generateTradeSignal(analysis, series.candles, Number.isFinite(riskPercent) ? riskPercent : 1); const model = 'gemini-3.8-flash'; if (!genAI) return res.json({ success: true, aiAvailable: false, analysis: { decision: 'WEAKEN', rationale: 'GEMINI_API_KEY não configurada; análise determinística disponível.', riskFlags: ['gemini_api_unavailable'], model: 'local-fallback' }, signal }); const prompt = buildQuantAnalystPrompt({ analysis, signal }); const response = await genAI.models.generateContent({ model, contents: prompt }); const quantAnalyst = parseQuantAnalystResponse(response.text || '', model); return res.json({ success: true, aiAvailable: true, analysis: quantAnalyst, signal, generatedAt: Date.now() }); } catch (error: any) { console.error('Gemini Quant Analyst error:', error); return res.status(502).json({ success: false, error: error?.message || 'Falha no Quant Analyst.' }); } });
app.get('/api/backtest', async (req, res) => { try { const symbol = String(req.query.symbol || 'BTC/USDT').toUpperCase(); if (!/^[A-Z0-9]+\/[A-Z0-9]+$/.test(symbol)) return res.status(400).json({ success: false, error: 'Símbolo inválido. Use o formato BTC/USDT.' }); const requestedDays = Number.parseInt(String(req.query.days || '60'), 10); const days = Number.isFinite(requestedDays) ? Math.max(7, Math.min(requestedDays, 90)) : 60; const endTime = Date.now(); const startTime = endTime - days * 86_400_000; const [candles, historicalFunding] = await Promise.all([fetchHistoricalBinanceCandles(symbol, '15m', startTime, endTime), fetchHistoricalBinanceFunding(symbol, startTime, endTime)]); if (candles.length < 300) return res.status(422).json({ success: false, error: `Histórico insuficiente: ${candles.length} candles.` }); const result = runHistoricalBacktest({ symbol, candles, initialCapital: 10_000, riskPerTradePercent: 1, minScore: 35, minConfidence: 50, atrStopMultiple: 1.5, rewardRisk: 2, maxHoldingBars: 32, warmupBars: 220, historicalFunding }); return res.json({ success: true, source: 'Binance real OHLCV + Binance Futures historical funding', parameters: { symbol, timeframe: '15m', days, candles: candles.length, fundingEvents: historicalFunding.length, riskPerTradePercent: 1, rewardRisk: 2, maxHoldingBars: 32 }, ...result }); } catch (error: any) { console.error('Historical backtest error:', error); return res.status(502).json({ success: false, error: error?.message || 'Falha ao executar backtest histórico real.' }); } });
app.get('/api/quant/lab', async (req, res) => { try { const symbol = String(req.query.symbol || 'BTC/USDT').toUpperCase(); const requestedDays = Number.parseInt(String(req.query.days || '30'), 10); const days = Number.isFinite(requestedDays) ? Math.max(7, Math.min(requestedDays, 90)) : 30; if (!/^[A-Z0-9]+\/[A-Z0-9]+$/.test(symbol)) return res.status(400).json({ success: false, error: 'Símbolo inválido. Use o formato BTC/USDT.' }); const endTime = Date.now(); const startTime = endTime - days * 86_400_000; const [candles, historicalFunding] = await Promise.all([fetchHistoricalBinanceCandles(symbol, '15m', startTime, endTime), fetchHistoricalBinanceFunding(symbol, startTime, endTime)]); if (candles.length < 300) return res.status(422).json({ success: false, error: `Histórico insuficiente: ${candles.length} candles.` }); const options = { symbol, candles, initialCapital: 10_000, riskPerTradePercent: 1, minScore: 35, minConfidence: 50, atrStopMultiple: 1.5, rewardRisk: 2, maxHoldingBars: 32, warmupBars: 220, historicalFunding } as const; const backtest = runHistoricalBacktest(options); const paperState = paperTradingLoop.getEngine().getState(); const lab = buildQuantitativeLab(backtest, paperState, candles); return res.json({ success: true, source: 'Binance real OHLCV + Binance Futures historical funding • Quant Lab completo', parameters: { symbol, timeframe: '15m', days, candles: candles.length, fundingEvents: historicalFunding.length, riskPerTradePercent: 1, rewardRisk: 2, maxHoldingBars: 32 }, ...lab }); } catch (error: any) { console.error('Quantitative lab error:', error); return res.status(502).json({ success: false, error: error?.message || 'Falha ao executar Quant Lab.' }); } });
app.get('/api/quant/validate', async (req, res) => { try { const symbol = String(req.query.symbol || 'BTC/USDT').toUpperCase(); const requestedDays = Number.parseInt(String(req.query.days || '180'), 10); const days = Number.isFinite(requestedDays) ? Math.max(90, Math.min(requestedDays, 180)) : 180; const trainPercent = Number(req.query.trainPercent ?? 70); if (!/^[A-Z0-9]+\/[A-Z0-9]+$/.test(symbol)) return res.status(400).json({ success: false, error: 'Símbolo inválido. Use o formato BTC/USDT.' }); const endTime = Date.now(); const startTime = endTime - days * 86_400_000; const [candles, historicalFunding] = await Promise.all([fetchHistoricalBinanceCandles(symbol, '15m', startTime, endTime), fetchHistoricalBinanceFunding(symbol, startTime, endTime)]); if (candles.length < 5000) return res.status(422).json({ success: false, error: `Histórico insuficiente para OOS multi-regime: ${candles.length} candles. Recomenda-se pelo menos 5.000.` }); const baseOptions = { initialCapital: 10_000, riskPerTradePercent: 1, minScore: 35, minConfidence: 50, atrStopMultiple: 1.5, rewardRisk: 2, maxHoldingBars: 32, warmupBars: 220, historicalFunding }; const validation = validateSelectedParameters(symbol, candles, baseOptions, Number.isFinite(trainPercent) ? trainPercent : 70); return res.json({ success: true, source: 'Binance real OHLCV + Binance Futures historical funding • extended multi-regime OOS validation', parameters: { symbol, timeframe: '15m', days, candles: candles.length, fundingEvents: historicalFunding.length, trainPercent: validation.split.trainPercent, regimeWindowDays: days }, ...validation }); } catch (error: any) { console.error('Parameter OOS validation error:', error); return res.status(502).json({ success: false, error: error?.message || 'Falha na validação OOS multi-regime.' }); } });
app.get('/api/notifications', (_req, res) => res.json({ notifications: cachedNotifications, unreadCount: cachedNotifications.filter(n => !n.read).length })); app.post('/api/notifications/mark-read', (_req, res) => { cachedNotifications.forEach(n => { n.read = true; }); res.json({ success: true, unreadCount: 0 }); }); app.post('/api/notifications/clear', (_req, res) => { cachedNotifications = []; res.json({ success: true, count: 0 }); });
async function startServer() { if (process.env.NODE_ENV !== 'production') { const vite = await createViteServer({ server: { middlewareMode: true }, appType: 'spa' }); app.use(vite.middlewares); } else { const distPath = path.join(process.cwd(), 'dist'); app.use(express.static(distPath)); app.get('*', (_req, res) => res.sendFile(path.join(distPath, 'index.html'))); } app.listen(PORT, '0.0.0.0', () => console.log(`[The God Protocol v2026] Server running on http://0.0.0.0:${PORT}`)); }
startServer();