import { useCallback, useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import { Activity, RefreshCw, ShieldCheck, ShieldAlert, TrendingDown, TrendingUp, FlaskConical } from 'lucide-react';

type Lab = {
  backtest?: { trades: number; winRatePercent: number; profitFactor: number; netPnlPercent: number; expectancyR: number; maxDrawdownPercent: number; sharpeRatio: number; sortinoRatio: number; fees: number; slippage: number; equityCurve?: Array<{ date: string; equity: number }> };
  paper?: { trades: number; netPnlPercent: number; expectancyR: number; maxDrawdownPercent: number; profitFactor: number; equity: number; halted: boolean };
  comparison?: { status: string; expectancyDeltaR: number; winRateDeltaPercent: number; reasons: string[] };
  quality?: { score: number; grade: string; checks: string[]; warnings: string[] };
  statistics?: { sampleSize: number; meanR: number; medianR: number; stdDevR: number; expectancyCi95R: [number, number] | null; maxConsecutiveLosses: number; directions: Array<{ direction: string; trades: number; winRatePercent: number; expectancyR: number; profitFactor: number }>; warnings: string[] };
  robustness?: { sampleSize: number; bootstrapCi95R: [number, number] | null; stabilityScore: number; grade: string; warnings: string[] };
  timeSeries?: { periods: Array<{ period: string; trades: number; netR: number; expectancyR: number; winRatePercent: number }>; consistencyPercent: number; positivePeriods: number; negativePeriods: number; warnings: string[] };
  walkForward?: { windows: Array<{ index: number; testExpectancyR: number; testProfitFactor: number; status: string }>; outOfSampleTrades: number; outOfSampleExpectancyR: number; outOfSampleProfitFactor: number; consistencyPercent: number; grade: string; warnings: string[] };
  stressTest?: { scenarios: Array<{ label: string; netProfitPercent: number; expectancyR: number; profitFactor: number; status: string }>; grade: string; warnings: string[] };
  monteCarlo?: { simulations: number; sampleSize: number; medianFinalR: number; p05FinalR: number; p95FinalR: number; medianMaxDrawdownR: number; p95MaxDrawdownR: number; probabilityOfLossPercent: number; probabilityOfDrawdownOver10RPercent: number; grade: string; warnings: string[] };
};
type Param = { minScore: number; minConfidence: number; atrStopMultiple: number; rewardRisk: number; maxHoldingBars: number; expectancyR: number; profitFactor: number; maxDrawdownPercent: number; trades: number };
type Validation = {
  split?: { trainCandles: number; holdoutCandles: number; trainPercent: number };
  optimization?: { selected: Param | null; baseline: Param | null; grade: string; warnings: string[] };
  baselineHoldout?: { trades: number; expectancyR: number; profitFactor: number; maxDrawdownPercent: number; netProfitPercent: number };
  selectedHoldout?: { trades: number; expectancyR: number; profitFactor: number; maxDrawdownPercent: number; netProfitPercent: number } | null;
  monteCarlo?: { grade: string; probabilityOfLossPercent: number; probabilityOfDrawdownOver10RPercent: number; p05FinalR: number; p95MaxDrawdownR: number } | null;
  stressTest?: { grade: string; scenarios: Array<{ label: string; status: string; expectancyR: number; profitFactor: number }> } | null;
  comparison?: { expectancyDeltaR: number; netProfitDeltaPercent: number; drawdownDeltaPercent: number; selectedBeatsBaseline: boolean };
  overfittingGuard?: { level: string; score: number; expectancyRetentionPercent: number; profitFactorRetentionPercent: number; tradeCount: number; warnings: string[] };
  significance?: { sampleSize: number; meanR: number; bootstrapCi95R: { low: number; high: number } | null; probabilityPositiveExpectancyPercent: number; probabilityPositiveDeltaPercent: number; baselineDeltaCi95R: { low: number; high: number } | null; status: string; warnings: string[] };
  regimeValidation?: { coveredRegimes: number; evaluatedRegimes: number; positiveRegimes: number; coveragePercent: number; consistencyPercent: number; worstExpectancyR: number; status: string; warnings: string[] };
  multiRegimeValidation?: { totalCells: number; coveredCells: number; evaluatedCells: number; positiveCells: number; coveragePercent: number; consistencyPercent: number; worstExpectancyR: number; status: string; minimumTradesPerCell: number; fundingEvents: number; fundingCoveragePercent: number; fundingSources: Record<string, number>; firstFundingTimestamp: number | null; lastFundingTimestamp: number | null; warnings: string[]; cells: Array<{ key: string; trend: string; volatility: string; funding: string; trades: number; winRatePercent: number; netR: number; expectancyR: number; profitFactor: number; maxDrawdownR: number }> };
  verdict?: string;
  warnings?: string[];
};
const pct = (v?: number) => Number.isFinite(v) ? `${(v as number).toFixed(2)}%` : '—';
const num = (v?: number, d = 2) => Number.isFinite(v) ? (v as number).toFixed(d) : '—';
const money = (v?: number) => Number.isFinite(v) ? `$${(v as number).toLocaleString('en-US', { maximumFractionDigits: 2 })}` : '—';
const pf = (v?: number) => Number.isFinite(v) ? (v as number).toFixed(2) : v === Infinity ? '∞' : v === -Infinity ? '-∞' : '—';
const gradeClass = (g?: string) => g === 'A' || g === 'ROBUST' || g === 'PASS' || g === 'SIGNIFICANT' || g === 'LOW' ? 'text-emerald-300' : g === 'B' || g === 'PROMISING' || g === 'MODERATE' || g === 'CAUTION' || g === 'MIXED' || g === 'WEAK' ? 'text-amber-300' : g === 'INSUFFICIENT_DATA' ? 'text-slate-500' : 'text-rose-300';

export function QuantitativeLabPanel() {
  const [lab, setLab] = useState<Lab | null>(null);
  const [validation, setValidation] = useState<Validation | null>(null);
  const [days, setDays] = useState(30);
  const [loading, setLoading] = useState(false);
  const [validating, setValidating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [validationError, setValidationError] = useState<string | null>(null);
  const refresh = useCallback(async () => { setLoading(true); setError(null); try { const res = await fetch(`/api/quant-lab?symbol=BTC%2FUSDT&days=${days}`); const data = await res.json(); if (!res.ok || !data.success) throw new Error(data.error || 'Falha no Quant Lab'); setLab(data); } catch (e) { setError(e instanceof Error ? e.message : 'Falha ao carregar laboratório'); } finally { setLoading(false); } }, [days]);
  const validate = useCallback(async () => { setValidating(true); setValidationError(null); try { const res = await fetch(`/api/quant/validate?symbol=BTC%2FUSDT&days=90&trainPercent=70`); const data = await res.json(); if (!res.ok || !data.success) throw new Error(data.error || 'Falha na validação OOS'); setValidation(data); } catch (e) { setValidationError(e instanceof Error ? e.message : 'Falha na validação OOS'); } finally { setValidating(false); } }, []);
  useEffect(() => { refresh(); }, [refresh]);
  const bt = lab?.backtest; const pp = lab?.paper; const q = lab?.quality; const equity = bt?.equityCurve ?? [];
  const v = validation; const selected = v?.optimization?.selected; const baseline = v?.optimization?.baseline; const verdict = v?.verdict;
  const mr = v?.multiRegimeValidation; const sig = v?.significance; const overfit = v?.overfittingGuard; const regime = v?.regimeValidation;
  const topCells = [...(mr?.cells ?? [])].filter(c => c.trades >= (mr?.minimumTradesPerCell ?? 10)).sort((a,b) => b.expectancyR - a.expectancyR).slice(0, 3);
  const weakCells = [...(mr?.cells ?? [])].filter(c => c.trades >= (mr?.minimumTradesPerCell ?? 10)).sort((a,b) => a.expectancyR - b.expectancyR).slice(0, 3);
  return <section className="fixed bottom-4 left-4 z-50 w-[min(820px,calc(100vw-2rem))] rounded-2xl border border-slate-700 bg-slate-950/95 shadow-2xl shadow-black/50 backdrop-blur-xl overflow-hidden font-mono">
    <header className="flex items-center justify-between px-4 py-3 border-b border-slate-800 bg-slate-900/90"><div className="flex items-center gap-2"><Activity className="w-4 h-4 text-cyan-300" /><b className="text-sm text-white">QUANT LAB v5</b><span className="text-[10px] text-slate-500">BTC/USDT • DECISÃO QUANTITATIVA • PAPER ONLY</span></div><div className="flex items-center gap-1"><button onClick={validate} disabled={validating} className="flex items-center gap-1 px-2 py-1.5 rounded-lg bg-cyan-400/10 border border-cyan-400/30 text-cyan-200 text-[9px] disabled:opacity-40"><FlaskConical className="w-3.5 h-3.5"/>{validating ? 'VALIDANDO...' : 'VALIDAR OOS'}</button><button disabled={loading} onClick={refresh} className="p-1.5 rounded-lg bg-slate-800 border border-slate-700 disabled:opacity-40"><RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} /></button></div></header>
    <div className="p-4 space-y-3 max-h-[78vh] overflow-y-auto">
      <div className="flex items-center gap-2"><span className="text-[10px] text-slate-500">HISTÓRICO</span>{[7,30,60,90].map(vv => <button key={vv} onClick={() => setDays(vv)} className={`px-2 py-1 rounded text-[10px] border ${days===vv?'border-cyan-400/50 bg-cyan-400/10 text-cyan-200':'border-slate-800 bg-slate-900 text-slate-500'}`}>{vv}D</button>)}</div>
      {error && <div className="rounded-lg border border-rose-500/30 bg-rose-500/10 p-2 text-[10px] text-rose-300">{error}</div>}
      {validationError && <div className="rounded-lg border border-rose-500/30 bg-rose-500/10 p-2 text-[10px] text-rose-300">OOS: {validationError}</div>}
      <div className="grid grid-cols-4 gap-2"><Metric label="TRADES" value={bt?.trades ?? 0}/><Metric label="WIN RATE" value={pct(bt?.winRatePercent)}/><Metric label="PF" value={pf(bt?.profitFactor)}/><Metric label="EXPECTANCY" value={`${num(bt?.expectancyR)}R`} positive={(bt?.expectancyR ?? 0)>0}/></div>
      <div className="grid grid-cols-4 gap-2"><Metric label="NET P&L" value={pct(bt?.netPnlPercent)} positive={(bt?.netPnlPercent ?? 0)>=0}/><Metric label="MAX DD" value={pct(bt?.maxDrawdownPercent)}/><Metric label="SHARPE" value={num(bt?.sharpeRatio)}/><Metric label="SORTINO" value={num(bt?.sortinoRatio)}/></div>
      <div className="rounded-xl border border-slate-800 bg-slate-900/60 p-3"><div className="flex justify-between text-[10px] text-slate-500 mb-2"><span>EQUITY CURVE</span><span>{equity.length ? `${money(equity[0].equity)} → ${money(equity.at(-1)?.equity)}` : 'sem dados'}</span></div><div className="flex items-end gap-1 h-14">{equity.slice(-56).map((p,i,a)=>{const min=Math.min(...a.map(x=>x.equity));const max=Math.max(...a.map(x=>x.equity));const h=max>min?10+((p.equity-min)/(max-min))*90:50;return <div key={`${p.date}-${i}`} title={`${p.date} ${money(p.equity)}`} className="flex-1 rounded-t bg-cyan-400/70" style={{height:`${h}%`}}/>})}</div></div>
      <div className="grid grid-cols-3 gap-2"><DecisionCard icon={q?.grade==='A'||q?.grade==='B'?<ShieldCheck/>:<ShieldAlert/>} label="QUALITY" value={q?.grade ?? '—'} detail={`${q?.score ?? 0}/100`} grade={q?.grade}/><DecisionCard label="ROBUSTEZ" value={lab?.robustness?.grade ?? '—'} detail={`${num(lab?.robustness?.stabilityScore)}%`} grade={lab?.robustness?.grade}/><DecisionCard label="MONTE CARLO" value={lab?.monteCarlo?.grade ?? '—'} detail={`perda ${pct(lab?.monteCarlo?.probabilityOfLossPercent)}`} grade={lab?.monteCarlo?.grade}/></div>
      <div className="rounded-xl border border-cyan-400/20 bg-cyan-400/5 p-3"><div className="flex items-center justify-between mb-2"><div className="flex items-center gap-2 text-[10px] text-cyan-200"><FlaskConical className="w-3.5 h-3.5"/>VALIDAÇÃO OOS</div><b className={`text-sm ${gradeClass(verdict)}`}>{verdict ?? 'NÃO EXECUTADA'}</b></div>{v ? <>
        <div className="grid grid-cols-4 gap-2 mb-2"><Metric label="TREINO" value={v.split?.trainCandles ?? 0}/><Metric label="HOLDOUT" value={v.split?.holdoutCandles ?? 0}/><Metric label="TRAIN %" value={pct(v.split?.trainPercent)}/><Metric label="SEL. > BASE" value={v.comparison?.selectedBeatsBaseline ? 'SIM' : 'NÃO'} positive={v.comparison?.selectedBeatsBaseline}/></div>
        <div className="grid grid-cols-2 gap-2"><ParamCard title="PARÂMETRO SELECIONADO" data={selected}/><ParamCard title="BASELINE" data={baseline}/></div>
        <div className="grid grid-cols-3 gap-2 mt-2"><DecisionCard label="OOS" value={verdict ?? '—'} detail={`ΔExp ${num(v.comparison?.expectancyDeltaR)}R`} grade={verdict}/><DecisionCard label="MONTE CARLO" value={v.monteCarlo?.grade ?? '—'} detail={`perda ${pct(v.monteCarlo?.probabilityOfLossPercent)}`} grade={v.monteCarlo?.grade}/><DecisionCard label="STRESS" value={v.stressTest?.grade ?? '—'} detail={`${v.stressTest?.scenarios?.length ?? 0} cenários`} grade={v.stressTest?.grade}/></div>
        <div className="grid grid-cols-3 gap-2 mt-2"><DecisionCard label="SIGNIFICÂNCIA" value={sig?.status ?? '—'} detail={`P(Exp>0) ${pct(sig?.probabilityPositiveExpectancyPercent)}`} grade={sig?.status}/><DecisionCard label="OVERFITTING" value={overfit?.level ?? '—'} detail={`score ${num(overfit?.score,0)} • ret. ${pct(overfit?.expectancyRetentionPercent)}`} grade={overfit?.level}/><DecisionCard label="REGIMES" value={regime?.status ?? '—'} detail={`${num(regime?.consistencyPercent)}% positivos`} grade={regime?.status}/></div>
        <div className="mt-2 rounded-lg border border-slate-800 bg-slate-950/60 p-2"><div className="grid grid-cols-4 gap-2 text-[9px]"><Metric label="OOS N" value={sig?.sampleSize ?? v.selectedHoldout?.trades ?? 0}/><Metric label="IC 95% EXP" value={sig?.bootstrapCi95R ? `${num(sig.bootstrapCi95R.low)} / ${num(sig.bootstrapCi95R.high)}R` : '—'}/><Metric label="P(Δ>0)" value={pct(sig?.probabilityPositiveDeltaPercent)}/><Metric label="OOS PF" value={pf(v.selectedHoldout?.profitFactor)}/></div></div>
        <div className="mt-2 rounded-lg border border-slate-800 bg-slate-950/60 p-2"><div className="flex justify-between text-[9px] text-slate-500 mb-1"><span>MULTI-REGIME</span><span>{mr?.evaluatedCells ?? 0}/{mr?.totalCells ?? 0} células avaliadas • mínimo {mr?.minimumTradesPerCell ?? 10}T</span></div><div className="grid grid-cols-5 gap-2"><Metric label="STATUS" value={mr?.status ?? '—'}/><Metric label="COBERTURA" value={pct(mr?.coveragePercent)}/><Metric label="CONSISTÊNCIA" value={pct(mr?.consistencyPercent)}/><Metric label="WORST EXP" value={`${num(mr?.worstExpectancyR)}R`} positive={(mr?.worstExpectancyR ?? 0)>0}/><Metric label="CÉLULAS +" value={`${mr?.positiveCells ?? 0}`}/></div><div className="grid grid-cols-2 gap-2 mt-2"><CellList title="MELHORES CÉLULAS" cells={topCells}/><CellList title="PIORAS CÉLULAS" cells={weakCells}/></div></div>
        <div className="mt-2 rounded-lg border border-slate-800 bg-slate-950/60 p-2"><div className="text-[9px] text-slate-500 mb-1">FUNDING / DERIVATIVOS</div><div className="grid grid-cols-4 gap-2"><Metric label="EVENTOS" value={mr?.fundingEvents ?? 0}/><Metric label="COBERTURA" value={pct(mr?.fundingCoveragePercent)}/><Metric label="BINANCE" value={mr?.fundingSources?.['binance-futures'] ?? 0}/><Metric label="OKX" value={mr?.fundingSources?.['okx-swap'] ?? 0}/></div></div>
        <div className="mt-2 text-[9px] text-slate-500">OOS Δ P&L: {pct(v.comparison?.netProfitDeltaPercent)} • Δ DD: {pct(v.comparison?.drawdownDeltaPercent)} • MC P05: {num(v.monteCarlo?.p05FinalR)}R • P95 DD: {num(v.monteCarlo?.p95MaxDrawdownR)}R • PF retenção: {pct(overfit?.profitFactorRetentionPercent)}</div>
        {(v.warnings?.length || v.optimization?.warnings?.length) ? <div className="mt-2 text-[9px] text-amber-300">{[...(v.warnings ?? []), ...(v.optimization?.warnings ?? [])].slice(0,4).join(' • ')}</div> : null}
      </> : <div className="text-[9px] text-slate-500">Clique em VALIDAR OOS. A validação usa janela cronológica, compara baseline contra parâmetros selecionados e não altera os parâmetros ativos.</div>}</div>
      <div className="grid grid-cols-2 gap-2"><div className="rounded-xl border border-slate-800 bg-slate-900/60 p-3"><div className="flex justify-between mb-2"><span className="text-[10px] text-slate-500">LONG × SHORT</span><span className="text-[9px] text-slate-600">amostra {lab?.statistics?.sampleSize ?? 0}</span></div><div className="grid grid-cols-2 gap-2">{(lab?.statistics?.directions ?? []).map(d=><div key={d.direction} className="rounded-lg border border-slate-800 bg-slate-950 p-2"><b className="text-[10px] text-white">{d.direction}</b><div className="grid grid-cols-3 gap-1 mt-2"><Metric label="N" value={d.trades}/><Metric label="WR" value={pct(d.winRatePercent)}/><Metric label="EXP" value={`${num(d.expectancyR)}R`} positive={d.expectancyR>0}/></div></div>)}</div></div><Mini title="WALK-FORWARD / OOS" grade={lab?.walkForward?.grade} lines={[`Trades OOS: ${lab?.walkForward?.outOfSampleTrades ?? 0}`,`Expectancy: ${num(lab?.walkForward?.outOfSampleExpectancyR)}R`,`PF: ${pf(lab?.walkForward?.outOfSampleProfitFactor)}`,`Consistência: ${pct(lab?.walkForward?.consistencyPercent)}`]}/></div>
      <div className="grid grid-cols-2 gap-2"><Mini title="STRESS TEST" grade={lab?.stressTest?.grade} lines={(lab?.stressTest?.scenarios ?? []).map(s=>`${s.label}: ${s.status} • ${num(s.expectancyR)}R`)}/><Mini title="MONTE CARLO" grade={lab?.monteCarlo?.grade} lines={[`P(Perda): ${pct(lab?.monteCarlo?.probabilityOfLossPercent)}`,`P(DD>10R): ${pct(lab?.monteCarlo?.probabilityOfDrawdownOver10RPercent)}`,`P05 final: ${num(lab?.monteCarlo?.p05FinalR)}R`]}/></div>
      <div className="rounded-xl border border-slate-800 bg-slate-900/60 p-3"><div className="flex items-center gap-2 text-[10px] text-slate-500 mb-2"><TrendingUp className="w-3 h-3"/>ESTABILIDADE TEMPORAL</div><div className="grid grid-cols-4 gap-2">{(lab?.timeSeries?.periods ?? []).slice(-8).map(p=><div key={p.period} className="text-center"><span className="block text-[8px] text-slate-600">{p.period}</span><b className={p.expectancyR>=0?'text-emerald-300':'text-rose-300'}>{num(p.expectancyR)}R</b><span className="block text-[8px] text-slate-600">{p.trades}T</span></div>)}</div></div>
      <div className="grid grid-cols-4 gap-2 text-[9px] text-slate-500"><Metric label="OOS PF" value={pf(lab?.walkForward?.outOfSampleProfitFactor)}/><Metric label="MC P05" value={`${num(lab?.monteCarlo?.p05FinalR)}R`}/><Metric label="MC P95 DD" value={`${num(lab?.monteCarlo?.p95MaxDrawdownR)}R`}/><Metric label="P(DD>10R)" value={pct(lab?.monteCarlo?.probabilityOfDrawdownOver10RPercent)}/></div>
      <div className="rounded-lg border border-slate-800 p-2 text-[9px] text-slate-500"><b className="text-slate-400">ALERTA:</b> {q?.warnings?.length ? q.warnings.slice(0,3).join(' • ') : 'Nenhum alerta de qualidade do backtest.'}</div>
      <div className="flex items-center justify-between text-[9px] text-slate-600"><span>Paper: {pp?.trades ?? 0} trades • equity {money(pp?.equity)} • {pp?.halted ? 'HALTED' : 'ACTIVE'}</span><span>BT × Paper: {lab?.comparison?.status ?? '—'}</span></div>
      <div className="flex items-center gap-2 text-[9px] text-slate-600"><TrendingDown className="w-3 h-3"/>Parâmetros OOS são candidatos. PASS não ativa execução financeira.</div>
    </div>
  </section>;
}
function Metric({label,value,positive}:{label:string;value:string|number;positive?:boolean}){return <div className="rounded-lg bg-slate-950 border border-slate-800 p-2"><span className="block text-[8px] text-slate-500">{label}</span><b className={`text-[11px] ${positive===true?'text-emerald-300':positive===false?'text-rose-300':'text-slate-200'}`}>{value}</b></div>}
function DecisionCard({icon,label,value,detail,grade}:{icon?:ReactNode;label:string;value:string;detail:string;grade?:string}){return <div className="rounded-xl border border-slate-800 bg-slate-900/60 p-3">{icon&&<span className={gradeClass(grade)}>{icon}</span>}<span className="block text-[8px] text-slate-500">{label}</span><b className={`text-sm ${gradeClass(grade)}`}>{value}</b><span className="block text-[9px] text-slate-600">{detail}</span></div>}
function Mini({title,grade,lines}:{title:string;grade?:string;lines:string[]}){return <div className="rounded-xl border border-slate-800 bg-slate-900/60 p-3"><div className="text-[9px] text-slate-500">{title}</div><b className={`text-xs ${gradeClass(grade)}`}>{grade ?? '—'}</b>{lines.map(x=><div key={x} className="text-[9px] text-slate-500">{x}</div>)}</div>}
function ParamCard({title,data}:{title:string;data?:Param|null}){return <div className="rounded-lg border border-slate-800 bg-slate-950 p-2"><div className="text-[8px] text-slate-500 mb-1">{title}</div>{data?<div className="grid grid-cols-5 gap-1 text-[9px]"><span>S {data.minScore}</span><span>C {data.minConfidence}</span><span>ATR {num(data.atrStopMultiple)}</span><span>RR {num(data.rewardRisk)}</span><span>H {data.maxHoldingBars}</span><span className="text-emerald-300">E {num(data.expectancyR)}R</span><span>PF {pf(data.profitFactor)}</span><span>DD {pct(data.maxDrawdownPercent)}</span><span>N {data.trades}</span></div>:<span className="text-[9px] text-slate-600">sem seleção</span>}</div>}
function CellList({title,cells}:{title:string;cells:Validation['multiRegimeValidation']['cells']}){return <div className="rounded-lg border border-slate-800 p-2"><div className="text-[8px] text-slate-500 mb-1">{title}</div>{cells.map(c=><div key={c.key} className="flex items-center justify-between gap-2 text-[8px] border-t border-slate-800/60 py-1"><span className="text-slate-400 truncate">{c.trend}/{c.volatility}/{c.funding}</span><span className={c.expectancyR>0?'text-emerald-300':'text-rose-300'}>{num(c.expectancyR)}R • {c.trades}T</span></div>)}</div>}
