import type { HistoricalBacktestResult } from '../backtest/historicalBacktest.js';
import type { PaperTradingState } from '../paper/paperTradingEngine.js';
import type { Candle } from '../../src/types.js';
import { analyzeRegimes, type RegimeAnalyticsResult } from './regimeAnalytics.js';
import { analyzeStatistics, type StatisticalAnalysisResult } from './statisticalAnalysis.js';
import { analyzeRobustness, type RobustnessAnalysisResult } from './robustnessAnalysis.js';
import { analyzeTimeSeries, type TimeSeriesAnalysisResult } from './timeSeriesAnalysis.js';
import { runWalkForwardAnalysis, type WalkForwardAnalysisResult } from './walkForwardAnalysis.js';
import { runStressTest, type StressTestResult } from './stressTest.js';
import { analyzeMonteCarlo, type MonteCarloAnalysisResult } from './monteCarloAnalysis.js';
import type { RobustParameterSelectionResult } from './robustParameterSelection.js';

export interface QuantMetricSet { trades: number; winRatePercent: number; profitFactor: number; netPnl: number; netPnlPercent: number; expectancyR: number; averageR: number; maxDrawdownPercent: number; bestTradePnl: number; worstTradePnl: number; tp1HitRatePercent: number; tp2HitRatePercent: number; fees: number; slippage: number; }
export interface QuantitativeLabResult {
  generatedAt: number; symbol: string;
  backtest: QuantMetricSet & { initialCapital: number; finalCapital: number; periodDays: number; sharpeRatio: number; sortinoRatio: number; grossExpectancyR: number; tradeDistribution: { wins: number; losses: number; breakevens: number }; equityCurve: HistoricalBacktestResult['equityCurve'] };
  paper: QuantMetricSet & { initialCapital: number; equity: number; openPositions: number; halted: boolean; history: PaperTradingState['history'] };
  comparison: { netPnlDeltaPercent: number; winRateDeltaPercent: number; expectancyDeltaR: number; drawdownDeltaPercent: number; profitFactorDelta: number; status: 'ALIGNED' | 'DIVERGENT' | 'INSUFFICIENT_DATA'; reasons: string[] };
  quality: { score: number; grade: 'A' | 'B' | 'C' | 'D' | 'INSUFFICIENT_DATA'; checks: string[]; warnings: string[] };
  regimes: RegimeAnalyticsResult; statistics: StatisticalAnalysisResult; robustness: RobustnessAnalysisResult; timeSeries: TimeSeriesAnalysisResult; walkForward?: WalkForwardAnalysisResult; stressTest?: StressTestResult; monteCarlo?: MonteCarloAnalysisResult; parameterSelection: RobustParameterSelectionResult;
}
const finite = (v: number, fallback = 0) => Number.isFinite(v) ? v : fallback;
const round = (v: number, d = 4) => Number(finite(v).toFixed(d));
const delta = (a: number, b: number) => round(a - b);
function backtestMetrics(result: HistoricalBacktestResult): QuantitativeLabResult['backtest'] { const wins = result.trades.filter(t => t.pnlR > 0).length; const losses = result.trades.filter(t => t.pnlR < 0).length; return { trades: result.totalTrades, winRatePercent: round(result.winRate), profitFactor: finite(result.profitFactor), netPnl: round(result.finalCapital - result.initialCapital, 2), netPnlPercent: round(result.netProfitPercent), expectancyR: round(result.expectancyR), averageR: round(result.averageRR), maxDrawdownPercent: round(result.maxDrawdownPercent), bestTradePnl: result.trades.length ? round(Math.max(...result.trades.map(t => t.pnlPercent)), 4) : 0, worstTradePnl: result.trades.length ? round(Math.min(...result.trades.map(t => t.pnlPercent)), 4) : 0, tp1HitRatePercent: round(result.trades.filter(t => t.status === 'TP ATINGIDO').length / Math.max(1, result.totalTrades) * 100), tp2HitRatePercent: 0, fees: round(result.totalFeesPercent, 4), slippage: round(result.totalSlippagePercent, 4), initialCapital: result.initialCapital, finalCapital: result.finalCapital, periodDays: round(result.periodDays, 2), sharpeRatio: round(result.sharpeRatio), sortinoRatio: round(result.sortinoRatio), grossExpectancyR: round(result.grossExpectancyR), tradeDistribution: { wins, losses, breakevens: result.totalTrades - wins - losses }, equityCurve: result.equityCurve }; }
function paperMetrics(state: PaperTradingState): QuantitativeLabResult['paper'] { return { trades: state.stats.totalTrades, winRatePercent: round(state.stats.winRatePercent), profitFactor: finite(state.stats.profitFactor), netPnl: round(state.account.realizedPnl, 2), netPnlPercent: round(state.stats.netPnlPercent), expectancyR: round(state.stats.averageR), averageR: round(state.stats.averageR), maxDrawdownPercent: round(state.account.maxDrawdownPercent), bestTradePnl: round(state.stats.bestTradePnl, 4), worstTradePnl: round(state.stats.worstTradePnl, 4), tp1HitRatePercent: round(state.stats.tp1HitRatePercent), tp2HitRatePercent: round(state.stats.tp2HitRatePercent), fees: round(state.account.feesPaid, 4), slippage: round(state.account.slippagePaid, 4), initialCapital: state.account.initialCapital, equity: state.account.equity, openPositions: state.positions.length, halted: state.account.halted, history: state.history }; }
function buildComparison(backtest: QuantitativeLabResult['backtest'], paper: QuantitativeLabResult['paper']): QuantitativeLabResult['comparison'] { const common = { netPnlDeltaPercent: delta(paper.netPnlPercent, backtest.netPnlPercent), winRateDeltaPercent: delta(paper.winRatePercent, backtest.winRatePercent), expectancyDeltaR: delta(paper.expectancyR, backtest.expectancyR), drawdownDeltaPercent: delta(paper.maxDrawdownPercent, backtest.maxDrawdownPercent), profitFactorDelta: delta(paper.profitFactor, backtest.profitFactor) }; if (backtest.trades < 30 || paper.trades < 10) return { ...common, status: 'INSUFFICIENT_DATA', reasons: ['São necessários pelo menos 30 trades de backtest e 10 de Paper Trading para comparação robusta.'] }; const reasons: string[] = []; if (Math.abs(common.winRateDeltaPercent) > 15) reasons.push(`Win rate diverge ${round(Math.abs(common.winRateDeltaPercent), 2)} pontos percentuais.`); if (Math.abs(common.expectancyDeltaR) > 0.25) reasons.push(`Expectancy diverge ${round(Math.abs(common.expectancyDeltaR), 3)}R.`); if (Math.abs(common.drawdownDeltaPercent) > 5) reasons.push(`Drawdown máximo diverge ${round(Math.abs(common.drawdownDeltaPercent), 2)} pontos percentuais.`); return { ...common, status: reasons.length ? 'DIVERGENT' : 'ALIGNED', reasons: reasons.length ? reasons : ['Métricas principais estão dentro das bandas de alinhamento definidas.'] }; }
function assessQuality(result: HistoricalBacktestResult): QuantitativeLabResult['quality'] { if (result.totalTrades < 30) return { score: 0, grade: 'INSUFFICIENT_DATA', checks: [`Amostra: ${result.totalTrades} trades.`], warnings: ['Menos de 30 trades.'] }; let score = 0; const checks: string[] = []; const warnings: string[] = []; if (result.expectancyR > 0) { score += 25; checks.push('Expectancy positiva.'); } else warnings.push('Expectancy não é positiva.'); if (result.profitFactor > 1.2) { score += 20; checks.push('Profit Factor acima de 1.20.'); } else warnings.push('Profit Factor baixo.'); if (result.maxDrawdownPercent < 10) { score += 20; checks.push('Drawdown abaixo de 10%.'); } else warnings.push('Drawdown elevado.'); if (result.winRate >= 45) { score += 15; checks.push('Win rate >= 45%.'); } else warnings.push('Win rate abaixo de 45%.'); if (result.sharpeRatio > 1) { score += 10; checks.push('Sharpe acima de 1.'); } else warnings.push('Sharpe não supera 1.'); if (result.totalTrades >= 100) { score += 10; checks.push('Amostra >= 100 trades.'); } else warnings.push('Amostra ainda abaixo de 100 trades.'); const grade = score >= 85 ? 'A' : score >= 70 ? 'B' : score >= 50 ? 'C' : 'D'; return { score, grade, checks, warnings }; }
const baseOptions = { initialCapital: 10_000, riskPerTradePercent: 1, minScore: 35, minConfidence: 50, atrStopMultiple: 1.5, rewardRisk: 2, maxHoldingBars: 32, warmupBars: 220 } as const;
const emptySelection = (): RobustParameterSelectionResult => ({ candidates: [], selected: null, baseline: null, stableRegion: { minScore: [], minConfidence: [], atrStopMultiple: [], rewardRisk: [], maxHoldingBars: [] }, grade: 'INSUFFICIENT_DATA', warnings: ['Otimização de parâmetros é executada apenas pela validação OOS.'] });
export function buildQuantitativeLab(result: HistoricalBacktestResult, paperState: PaperTradingState, candles: Candle[]): QuantitativeLabResult {
  const backtest = backtestMetrics(result);
  const paper = paperMetrics(paperState);
  const deepAnalytics = candles.length <= 1200;
  const includeMonteCarlo = candles.length <= 6000;
  return {
    generatedAt: Date.now(), symbol: result.symbol, backtest, paper,
    comparison: buildComparison(backtest, paper), quality: assessQuality(result),
    regimes: analyzeRegimes(candles, result.trades), statistics: analyzeStatistics(result.trades), robustness: analyzeRobustness(result.trades), timeSeries: analyzeTimeSeries(result.trades),
    walkForward: deepAnalytics ? runWalkForwardAnalysis(result.symbol, candles, baseOptions) : undefined,
    stressTest: deepAnalytics ? runStressTest(result.symbol, candles, baseOptions) : undefined,
    monteCarlo: includeMonteCarlo ? analyzeMonteCarlo(result.trades, 3000, baseOptions.riskPerTradePercent) : undefined,
    parameterSelection: emptySelection(),
  };
}